annotations:
  screwdriver.cd/chainPR: true

shared:
    image: node:16
 
jobs:
  build1:
    description: "This is an example."
    requires: [ ~commit, ~pr ]
    steps:
      - hello: echo "Hello build1"
  build2:
    description: "This is a very very long example sentence."
    requires: [ ~commit, ~pr ]
    steps:
      - hello: echo "Hello build2"
  build3:
    requires: [ ~commit, ~pr ]
    steps:
      - hello: echo "Hello build2"
