annotations:
  screwdriver.cd/pipelineDescription: test
shared:
  image: node:12
 
jobs:
  build1:
    requires: [ ~commit, ~pr ]
    sourcePaths: ["screwdriver.yaml"]
    steps:
      - set-statusMessage: curl -X PUT -H "Authorization: Bearer $SD_TOKEN" -H "Content-Type: application/json" -d "{\"statusMessage\": \"This is test\"}" "${SD_API_URL}builds/${SD_BUILD_ID}"
      - echo "build"
      
