shared:
  image: node:12
 
jobs:
  OnlyExclude:
    requires: [ ~commit, ~pr ]
    sourcePaths: ["!test/", "!src/test"]
    steps:
      - echo "this is build1"
  
  editScrewdriver:
    requires: [ ~commit, ~pr ]
    sourcePaths: ["screwdriver.yaml"]
    steps:
      - echo "edit"
  
  mixCase:
    requires: [ ~commit, ~pr ]
    sourcePaths: ["!test/", "src/"]
    steps:
      - echo "Hello"
